### ISSUE TITLE
Repository is apparently missing tags

### ISSUE THREAD

**Issue by Eqqm4n** [kcuzner/midi-fader#1]
Hello-
After doing a make of the bootloader firmware for this project this error was reported : "fatal: No names found, cannot describe anything"

Doing a research of the error it turns out tags are missing from the project, which can happen if you do a shallow clone, however, this wasn't the case when I cloned it.  After none of the tricks for fixing missing tags worked I was able to solve this issue by adding --always to line 24 of firmwaregen.py.  One of the StackOverflow pundits suggested this might be an error in the repo itself and made this comment (to somebody else reporting this problem) ::
"It sounds like you're expecting git-describe to include the most recent tag and number of commits since that tag. However, the fatal: No names found message means you don't have any tags in your repository. You need to have at least one tag in the commit history in order for git describe to tell you the latest tag.

Just guessing, but perhaps you tagged a commit somewhere else, but never pushed the tag upstream (maybe you pushed the commit upstream, tagged it later, and didn't repush?). Now a new clone of your upstream is giving you this error (since it doesn't have any tag). If that's the case, you could try git push --tags from the repository that has the tag you want (where git describe is doing what you expect). Then do git pull on the repository that doesn't have the tag."

**Comment by kcuzner** [comment]
I will look at this soon, thank you for letting me know. I bet I did forget to post tags to GitHub.

**Comment by kcuzner** [comment]
Tags have been pushed
